<?php

return [
    'profilPosts' => [
        (object)[
            "id_posts" => 7720,
            "kategori_id" => 8,
            "judul_posts" => "Arti Lambang",
            "konten_posts" => <<<'HTML'
                <p><img style="float: left; margin-left: 0px; margin-right: 10px;" src="data/files/2_20080816_12294270.gif" alt="" width="138" height="161" />Berdasarkan PERDA No. II/1988 Pasal.3 tentang bentuk lambang daerah, maka lambang Kabupaten Pasuruan adalah sebagai berikut :</p>
                <p><span style="color: #006600;"><strong><em>Perisai</em></strong> </span>dengan warna hijau tua melambangkan sifat-sifat ketahanan dan ketabahan dalam mencapai kesejahteraan dan kedamaian.</p><p><strong><em>Bingkai</em></strong> warna hitam melambangkan garis-garis kebijaksanaan.</p>
                <p><span style="color: #666600;"><strong><em>Pita</em></strong> </span>bertuliskan "KABUPATEN PASURUAN", menunjukkan 1 daerah yang dilukiskan dalam lambang daerah.</p>
                <p><span style="color: #ffff00;"><span style="color: #ffcc00;"><strong><em>Bintang</em></strong></span> </span>yang terletak di tengah bagian atas, berwarna kuning emas, melambangkan "Ketuhanan Yang Maha Esa" yang harus dijunjung tinggi penuh keagungan, sedangkan pancaran sinarnya yang berjumlah 5 buah mencerminkan PANCASILA.</p>
                <p><span style="color: #0099ff;"><strong><em>Kubah</em></strong></span> berwarna biru muda, melambangkan tempat ibadah agama, secara khusus merupakan kehidupan spiritual masyarakat Kabupaten Pasuruan yang dilaksanakan dengan penuh ketakwaan.</p>
                <p><strong><em>Keris</em></strong> berwarna hitam dan kuning dengan garis tepi berwarna putih melambangkan sikap kepahlawanan.</p>
                <p><strong><em>Tebu dan Kapuk Randu</em></strong> melambangkan salah satu gambar penghasilan serta merupakan penunjang perekonomian yang menonjol bagi masyarakat di wilayah Kabupaten Pasuruan.</p>
                <p><span style="color: #006600;"><strong><em>Gunung, Daratan dan Laut</em></strong></span> masing-masing berwarna hijau tua, kuning tua dan biru tua, melambangkan bahwa kondisi geografis Kabupaten Pasuruan secara khusus sangat strategis dan terletak diantara ketiganya yang masing-masing mengandung potensi perekonomian yang dapat dikembangkan dan bersifat dinamis.</p>
                <p><strong><em>Pita Putih</em></strong> bertuliskan "Guna Karya Sarana Bhakti", merupakan motto pembangunan yang berarti kerja yang bermanfaat sebagai amal untuk berbakti.</p>
                HTML,
            "gambar_posts" => null,
            "counter_posts" => 0,
            "slug_posts" => "arti-lambang",
            "like_posts" => 0,
            "dislike_posts" => 0,
            "created_by" => 11,
            "updated_by" => null,
            "waktu_publish" => "2015-06-03 09:55:51",
            "created_at" => "2015-06-03 09:55:51",
            "updated_at" => null,
            "ori_name_gambar_posts" => null,
            "mimes_gambar_posts" => null,
            "extension_gambar_posts" => null,
            "ori_name_gambar_posts_2" => null,
            "mimes_gambar_posts_2" => null,
            "extension_gambar_posts_2" => null,
            "active" => 0,
            "gambar_posts_2" => null,
            "tumbnail" => null,
            "nama_kategori" => "Suara Warga",
            "tipe_kategori" => "halaman",
            "kategori_created_by" => null,
            "kategori_updated_by" => null,
        ],
        (object)[
            "id_posts" => 7721,
            "kategori_id" => 8,
            "judul_posts" => "Peta Pasuruan",
            "konten_posts" => '<p><img src="data/files/4_20091006_15505550.jpg" alt="" width="415" height="327" /></p>',
            "gambar_posts" => null,
            "counter_posts" => 0,
            "slug_posts" => "peta-pasuruan",
            "like_posts" => 0,
            "dislike_posts" => 0,
            "created_by" => 11,
            "updated_by" => null,
            "waktu_publish" => "2015-06-03 09:55:51",
            "created_at" => "2015-06-03 09:55:51",
            "updated_at" => null,
            "ori_name_gambar_posts" => null,
            "mimes_gambar_posts" => null,
            "extension_gambar_posts" => null,
            "ori_name_gambar_posts_2" => null,
            "mimes_gambar_posts_2" => null,
            "extension_gambar_posts_2" => null,
            "active" => 0,
            "gambar_posts_2" => null,
            "tumbnail" => null,
            "nama_kategori" => "Suara Warga",
            "tipe_kategori" => "halaman",
            "kategori_created_by" => null,
            "kategori_updated_by" => null,
        ],
        (object)[
            "id_posts" => 7722,
            "kategori_id" => 8,
            "judul_posts" => "Visi dan Misi",
            "konten_posts" => <<<'HTML'
                <p style="text-align: justify;"><b style="letter-spacing: 0.1px;">Visi :</b></p>
                <p style="text-align: justify;"><b><i>"Kabupaten Pasuruan yang Maju, Sejahtera dan ▶"</i></b></p>
                HTML,
            "gambar_posts" => "202502/7722-67be8826a29c5.jpg",
            "counter_posts" => 0,
            "slug_posts" => "visi-dan-misi",
            "like_posts" => 0,
            "dislike_posts" => 0,
            "created_by" => 11,
            "updated_by" => 8,
            "waktu_publish" => "2025-02-10 09:55:00",
            "created_at" => "2015-06-03 09:55:51",
            "updated_at" => "2025-02-26 04:24:58",
            "ori_name_gambar_posts" => null,
            "mimes_gambar_posts" => null,
            "extension_gambar_posts" => null,
            "ori_name_gambar_posts_2" => null,
            "mimes_gambar_posts_2" => null,
            "extension_gambar_posts_2" => null,
            "active" => 0,
            "gambar_posts_2" => null,
            "tumbnail" => null,
            "nama_kategori" => "Suara Warga",
            "tipe_kategori" => "halaman",
            "kategori_created_by" => null,
            "kategori_updated_by" => null,
        ],
        (object)[
            "id_posts" => 7724,
            "kategori_id" => 8,
            "judul_posts" => "Sejarah Singkat Kabupaten Pasuruan",
            "konten_posts" => <<<'HTML'
                <p center><strong>SEJARAH SINGKAT<br />
                HARI JADI KABUPATEN PASURUAN</strong></p>

                <p>&nbsp;</p>

                <p justify>Sejarah Kabupaten Pasuruan bermula dari Peradaban Kerajaan Kalingga atau Ho Ling yang diperintah oleh seorang Raja bernama Sima. P ▶</p>

                <p justify>Setelah masa kejayaan Kalingga berakhir muncullah Kerajaan Mataram Kuno dibawah kekuasaan Dinasti Sanjaya Tahun 856 Masehi dip ▶</p>

                <!-- truncated for brevity, kamu bisa ganti isi lengkapnya di sini -->
                <p center><img alt="" src="https://www.pasuruankab.go.id/data/files/bupati_pasuruan_web.jpg" /></p>
                HTML,
            "gambar_posts" => null,
            "counter_posts" => 0,
            "slug_posts" => "sejarah-singkat-kab-pasuruan",
            "like_posts" => 0,
            "dislike_posts" => 0,
            "created_by" => 11,
            "updated_by" => null,
            "waktu_publish" => "2021-08-09 09:55:51",
            "created_at" => "2021-08-09 09:55:51",
            "updated_at" => null,
            "ori_name_gambar_posts" => null,
            "mimes_gambar_posts" => null,
            "extension_gambar_posts" => null,
            "ori_name_gambar_posts_2" => null,
            "mimes_gambar_posts_2" => null,
            "extension_gambar_posts_2" => null,
            "active" => 0,
            "gambar_posts_2" => null,
            "tumbnail" => null,
            "nama_kategori" => "Suara Warga",
            "tipe_kategori" => "halaman",
            "kategori_created_by" => null,
            "kategori_updated_by" => null,
        ],
        (object)[
            "id_posts" => 11374,
            "kategori_id" => 8,
            "judul_posts" => "GAMBARAN UMUM KABUPATEN PASURUAN 2025",
            "konten_posts" => <<<'HTML'
            <p class="MsoNormal" style='margin-right: 0px; margin-left: 131.55pt; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: 0.1px; text-align: center;'><span style="margin: 0px; padding: 0px; border: none; outline: none; font-weight: bolder;"><span lang="EN-US" style='margin: 0px; padding: 0px; border: none; outline: none; font-size: 12pt; font-family: "Bookman Old Style", serif;'>GAMBARAN UMUM KABUPATEN PASURUAN</span></span><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;"><b>1. Aspek Geografis dan Demografis</b></span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;"><b>&nbsp; 1.1. Karakteristik Lokasi dan Wilayah</b></span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;"><b>&nbsp; &nbsp; &nbsp; &nbsp; A. Luas Dan Batas Wilayah Administrasi</b></span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;"><b><br></b></span></font></p><p class="MsoNormal" style="text-align: justify; margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;">Secara geografis, Kabupaten Pasuruan terletak pada koordinat 7,30'-8,30' Lintang Selatan dan 112'o30' -113'o30' Bujur Timur. Luas wilayah Kabupaten Pasuruan sebesar 148.612,07 Ha dengan batas administrasi Kabupaten Pasuruan meliputi:</span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;">Sebelah Utara : Kabupaten Sidoarjo, Kota Pasuruan, dan Selat Madura</span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;">Sebelah Timur : Kabupaten Probolinggo</span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;">Sebelah Selatan : Kabupaten Malang</span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;">Sebelah Barat : Kabupaten Mojokerto dan Kota Batu</span></font></p><p class="MsoNormal" style="margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><span style="margin: 0px; padding: 0px; border: none; outline: none;"><font color="#555555" face="Bookman Old Style, serif"><span lang="EN-US" style="margin: 0px; padding: 0px; border: none; outline: none; font-size: 16px;"></span></font></span></p><p class="MsoNormal" style="text-align: justify; margin-right: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em;"><font color="#555555" face="Bookman Old Style, serif"><span style="font-size: 16px;">Wilayah Kabupaten Pasuruan terbagi dalam wilayah adminsitratif sebanyak 24 kecamatan dan 365 kelurahan/desa sebagaimana dirincikan dalam tabel berikut:</span></font></p><p style='margin-right: 0px; margin-left: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: normal;'></p><p class="MsoNormal" style='margin-top: 0.15pt; margin-right: 0px; margin-left: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 8pt; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: 0.1px;'><span style="margin: 0px; padding: 0px; border: none; outline: none; letter-spacing: 0.1px; text-align: justify; text-indent: -18pt; font-size: 0.8125rem; font-weight: bolder;"><span lang="EN-US" style='margin: 0px; padding: 0px; border: none; outline: none; font-size: 12pt; font-family: "Bookman Old Style", serif;'>&nbsp;</span></span></p><p style='margin-right: 0px; margin-left: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: normal;'></p><p style='margin-right: 0px; margin-left: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: normal;'></p><p class="MsoNormal" style='margin-top: 0.1pt; margin-right: 0px; margin-left: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 5pt; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: 0.1px;'><span lang="EN-US" style="margin: 0px; padding: 0px; border: none; outline: none; font-size: 5.5pt;">&nbsp;</span></p><p style='margin-right: 0px; margin-left: 0px; padding: 0px; border: none; outline: none; position: relative; line-height: 1.8em; color: rgb(85, 85, 85); font-size: 16px; font-family: "Nunito Sans", sans-serif; letter-spacing: normal; text-align: center;'><img data-filename="tabel 1.png" src="https://www.pasuruankab.go.id/files/halaman/202502/11374-67be6dd15fc63.jpg" style="margin: 0px; padding: 0px; border-width: initial; border-color: initial; border-image: initial; outline: none; display: inline-block; max-width: 100%; height: auto;"></p><div style="margin: 0px; padding: 0px; border: none; outline: none; text-align: center;"><font color="#777777" face="Bookman Old Style, serif">Sumber: Badan Pusat Statistik Kabupaten Pasuruan, 2024</font></div>
            HTML,
            "gambar_posts" => "202502/11374-67bd78aa34b71.jpg",
            "counter_posts" => 0,
            "slug_posts" => "gambaran-umum-kabupaten-pasuruan-2025",
            "like_posts" => 0,
            "dislike_posts" => 0,
            "created_by" => 111900002,
            "updated_by" => 111900002,
            "waktu_publish" => "2025-02-25 10:20:00",
            "created_at" => "2025-02-25 04:02:00",
            "updated_at" => "2025-03-03 01:26:03",
            "ori_name_gambar_posts" => null,
            "mimes_gambar_posts" => null,
            "extension_gambar_posts" => null,
            "ori_name_gambar_posts_2" => null,
            "mimes_gambar_posts_2" => null,
            "extension_gambar_posts_2" => null,
            "active" => 0,
            "gambar_posts_2" => null,
            "tumbnail" => null,
            "nama_kategori" => "Suara Warga",
            "tipe_kategori" => "halaman",
            "kategori_created_by" => null,
            "kategori_updated_by" => null,
        ],
    ],
    'potensiPosts' => [
        (object) [
            'id_posts' => 101,
            'slug_posts' => 'pesona-matahari-terbit-di-gunung-bromo',
            'judul_posts' => 'Menyaksikan Pesona Matahari Terbit di Puncak Penanjakan Bromo',
            'waktu_publish' => '2025-08-21 09:15:00',
            'konten_posts' => '<b>Gunung Bromo</b> tetap menjadi magnet bagi wisatawan. Pemandangan matahari terbit dari Puncak Penanjakan adalah pengalaman magis yang tidak akan terlupakan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1596637012832-ac4354f7a293?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud'],
        ],
        (object) [
            'id_posts' => 102,
            'slug_posts' => 'petualangan-seru-di-taman-safari-prigen',
            'judul_posts' => 'Petualangan Seru dan Edukatif di Taman Safari Prigen',
            'waktu_publish' => '2025-08-20 14:30:00',
            'konten_posts' => '<b>Taman Safari Indonesia II</b> di Prigen, Pasuruan, menawarkan pengalaman unik berinteraksi langsung dengan satwa liar dari berbagai belahan dunia...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1579899139083-3403058a5940?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Rina Setyawati'],
        ],
        (object) [
            'id_posts' => 103,
            'slug_posts' => 'kesegaran-air-terjun-putuk-truno',
            'judul_posts' => 'Menikmati Kesegaran Alami di Air Terjun Putuk Truno',
            'waktu_publish' => '2025-08-19 11:00:00',
            'konten_posts' => 'Air Terjun Putuk Truno menjadi destinasi favorit untuk melepaskan penat. Suasana yang sejuk dan pemandangan asri menjadi daya tarik utamanya...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1501630834273-4b5604d2ee31?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud'],
        ],
        (object) [
            'id_posts' => 104,
            'slug_posts' => 'menjelajahi-sejarah-candi-jawi',
            'judul_posts' => 'Menjelajahi Jejak Sejarah di Candi Jawi',
            'waktu_publish' => '2025-08-18 16:45:00',
            'konten_posts' => 'Candi Jawi adalah peninggalan Kerajaan Singhasari yang megah. Arsitekturnya yang unik menggabungkan unsur Hindu dan Buddha...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1611099233629-0358a32a67a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono'],
        ],
        (object) [
            'id_posts' => 105,
            'slug_posts' => 'keindahan-tersembunyi-coban-baung',
            'judul_posts' => 'Keindahan Tersembunyi di Air Terjun Coban Baung',
            'waktu_publish' => '2025-08-17 09:00:00',
            'konten_posts' => 'Jelajahi keindahan alam yang masih alami di Coban Baung...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1673292293027-2bc4d1222e2a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 106,
            'slug_posts' => 'wisata-edukasi-kebun-raya-purwodadi',
            'judul_posts' => 'Belajar dan Bermain di Kebun Raya Purwodadi',
            'waktu_publish' => '2025-08-16 13:20:00',
            'konten_posts' => 'Koleksi tanaman langka dari seluruh Indonesia ada di sini...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1589252044539-4402d24a9f7e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Rina Setyawati']
        ],
        (object) [
            'id_posts' => 107,
            'slug_posts' => 'nikmatnya-kupang-lontong-khas-pasuruan',
            'judul_posts' => 'Wajib Coba: Nikmatnya Kuliner Kupang Lontong Pasuruan',
            'waktu_publish' => '2025-08-15 18:00:00',
            'konten_posts' => 'Kuliner legendaris yang selalu dirindukan para pelancong...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1664478239649-3a3d582af138?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 108,
            'slug_posts' => 'ritual-yadnya-kasada-suku-tengger',
            'judul_posts' => 'Melihat dari Dekat Ritual Sakral Yadnya Kasada',
            'waktu_publish' => '2025-08-14 10:00:00',
            'konten_posts' => 'Upacara adat Suku Tengger yang penuh makna dan menarik ribuan wisatawan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1618682570731-2357a75af144?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 109,
            'slug_posts' => 'pemandian-alam-banyu-biru',
            'judul_posts' => 'Relaksasi di Pemandian Alam Banyu Biru yang Legendaris',
            'waktu_publish' => '2025-08-13 15:10:00',
            'konten_posts' => 'Sumber mata air alami yang jernih dan dipercaya memiliki khasiat...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1579402242828-54335c9b7407?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Rina Setyawati']
        ],
        (object) [
            'id_posts' => 110,
            'slug_posts' => 'pesona-pantai-lekok-dan-ski-lumpur',
            'judul_posts' => 'Unik! Mencoba Ski di Atas Lumpur di Pantai Lekok',
            'waktu_publish' => '2025-08-12 12:00:00',
            'konten_posts' => 'Tradisi balap ski lumpur yang hanya ada di Pasuruan...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1673306852231-3e14f8495a12?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 111,
            'slug_posts' => 'agrowisata-bhakti-alam',
            'judul_posts' => 'Memetik Buah Segar Langsung dari Pohon di Bhakti Alam',
            'waktu_publish' => '2025-08-11 14:00:00',
            'konten_posts' => 'Wisata edukatif yang menyenangkan untuk seluruh keluarga...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 112,
            'slug_posts' => 'spot-foto-instagramable-pintu-langit',
            'judul_posts' => 'Berburu Foto Keren di Pintu Langit Prigen',
            'waktu_publish' => '2025-08-10 16:30:00',
            'konten_posts' => 'Pemandangan alam dari ketinggian yang memukau...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Rina Setyawati']
        ],
        (object) [
            'id_posts' => 113,
            'slug_posts' => 'menikmati-durian-khas-nongkojajar',
            'judul_posts' => 'Musim Durian Tiba! Menikmati Raja Buah di Nongkojajar',
            'waktu_publish' => '2025-08-09 11:45:00',
            'konten_posts' => 'Berbagai jenis durian lokal dengan rasa yang khas menanti Anda...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1603538421251-0a4731d273fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 114,
            'slug_posts' => 'jelajah-hutan-mangrove-nguling',
            'judul_posts' => 'Wisata Ekologi Menjelajahi Hutan Mangrove Nguling',
            'waktu_publish' => '2025-08-08 09:30:00',
            'konten_posts' => 'Menyusuri jembatan kayu di tengah rimbunnya hutan bakau...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1590602847833-2244a1773537?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 115,
            'slug_posts' => 'wisata-religi-makam-kyai-hamid',
            'judul_posts' => 'Wisata Religi dan Sejarah di Makam Kyai Hamid Pasuruan',
            'waktu_publish' => '2025-08-07 19:00:00',
            'konten_posts' => 'Mengenal lebih dekat ulama besar yang dihormati...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1678292026839-a87f176b6b47?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 116,
            'slug_posts' => 'the-pines-taman-dayu',
            'judul_posts' => 'Bersantai di Tengah Hutan Pinus The Pines Taman Dayu',
            'waktu_publish' => '2025-08-06 15:00:00',
            'konten_posts' => 'Tempat yang cocok untuk camping dan kegiatan outdoor...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1448375240586-882707db888b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Rina Setyawati']
        ],
        (object) [
            'id_posts' => 117,
            'slug_posts' => 'saygon-waterpark',
            'judul_posts' => 'Segarkan Hari dengan Bermain Air di Saygon Waterpark',
            'waktu_publish' => '2025-08-05 13:00:00',
            'konten_posts' => 'Berbagai wahana air seru untuk semua usia...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1571104528391-a18451a37c46?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 118,
            'slug_posts' => 'danau-ranu-grati',
            'judul_posts' => 'Menikmati Senja di Tepi Danau Ranu Grati',
            'waktu_publish' => '2025-08-04 17:30:00',
            'konten_posts' => 'Pemandangan danau vulkanik yang menenangkan jiwa...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 119,
            'slug_posts' => 'sentra-batik-pasuruan',
            'judul_posts' => 'Belajar Membatik di Sentra Batik Khas Pasuruan',
            'waktu_publish' => '2025-08-03 10:45:00',
            'konten_posts' => 'Melihat proses pembuatan batik tulis dengan motif yang unik...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1569943485662-1b606541f2a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Rina Setyawati']
        ],
        (object) [
            'id_posts' => 120,
            'slug_posts' => 'pasar-bunga-tutur',
            'judul_posts' => 'Pasar Bunga dan Sayur di Kawasan Agropolitan Tutur',
            'waktu_publish' => '2025-08-02 08:00:00',
            'konten_posts' => 'Surga bagi para pencinta tanaman hias dan produk pertanian segar...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1594780762632-49931a535805?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'pariwisata', 'nama_kategori' => 'Pariwisata'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 201,
            'slug_posts' => 'mebel-bukir-kualitas-ekspor',
            'judul_posts' => 'Mebel Bukir: Kualitas Ekspor dari Pengrajin Lokal',
            'waktu_publish' => '2025-08-25 09:00:00',
            'konten_posts' => 'Kawasan Bukir di Kota Pasuruan telah lama dikenal sebagai sentra industri mebel. Kualitas produknya telah diakui hingga pasar ekspor...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag'],
        ],
        (object) [
            'id_posts' => 202,
            'slug_posts' => 'kopi-kapiten-pasuruan',
            'judul_posts' => 'Kopi Kapiten Pasuruan: Aroma Khas dari Lereng Arjuno',
            'waktu_publish' => '2025-08-24 14:00:00',
            'konten_posts' => 'Kopi Kapiten dari Pasuruan, khususnya yang berasal dari lereng Gunung Arjuno, memiliki cita rasa dan aroma yang khas dan kuat...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1511920183276-5941b5a5b314?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono'],
        ],
        (object) [
            'id_posts' => 203,
            'slug_posts' => 'potensi-industri-pengolahan-hasil-laut',
            'judul_posts' => 'Menggali Potensi Industri Pengolahan Hasil Laut di Pesisir Pasuruan',
            'waktu_publish' => '2025-08-23 11:30:00',
            'konten_posts' => 'Dari ikan asap hingga terasi, industri hasil laut terus berkembang...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1596198189443-013141154366?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 204,
            'slug_posts' => 'inovasi-pabrik-sepatu-lokal',
            'judul_posts' => 'Inovasi dan Daya Saing Pabrik Sepatu Lokal di Pasuruan',
            'waktu_publish' => '2025-08-22 16:00:00',
            'konten_posts' => 'Menembus pasar nasional dengan kualitas yang tidak kalah saing...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1557564437-0946a468825a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Joko Susilo']
        ],
        (object) [
            'id_posts' => 205,
            'slug_posts' => 'kisah-sukses-umkm-keripik-buah',
            'judul_posts' => 'Kisah Sukses UMKM Keripik Buah dari Lekok',
            'waktu_publish' => '2025-08-21 10:15:00',
            'konten_posts' => 'Mengolah hasil panen lokal menjadi produk bernilai tinggi...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1661763103774-706013a113a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 206,
            'slug_posts' => 'industri-logam-warungdowo',
            'judul_posts' => 'Industri Logam Warungdowo: Pusat Pengecoran dan Permesinan',
            'waktu_publish' => '2025-08-20 13:45:00',
            'konten_posts' => 'Denyut nadi industri logam yang memasok berbagai kebutuhan manufaktur...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 207,
            'slug_posts' => 'perkembangan-industri-tekstil-gempol',
            'judul_posts' => 'Melihat Perkembangan Industri Tekstil di Kawasan Gempol',
            'waktu_publish' => '2025-08-19 09:30:00',
            'konten_posts' => 'Menjadi salah satu pilar penyerapan tenaga kerja di Pasuruan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1605170429437-63ad5258e7a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Joko Susilo']
        ],
        (object) [
            'id_posts' => 208,
            'slug_posts' => 'sentra-bordir-bangil',
            'judul_posts' => 'Keindahan Bordir dari Sentra Kerajinan Bangil',
            'waktu_publish' => '2025-08-18 15:00:00',
            'konten_posts' => 'Karya seni tangan yang menghiasi busana hingga perlengkapan rumah...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1620649197170-2353c07a4a2b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 209,
            'slug_posts' => 'pabrik-susu-nestle-kejayan',
            'judul_posts' => 'Kontribusi Pabrik Susu Nestle Kejayan bagi Peternak Lokal',
            'waktu_publish' => '2025-08-17 12:15:00',
            'konten_posts' => 'Kemitraan yang mensejahterakan ribuan peternak sapi perah...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1628038531393-d25a66a19f93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 210,
            'slug_posts' => 'industri-pengolahan-mangga-gedong-gincu',
            'judul_posts' => 'Dari Kebun ke Meja Makan: Industri Pengolahan Mangga Gedong Gincu',
            'waktu_publish' => '2025-08-16 11:00:00',
            'konten_posts' => 'Sirup, selai, dan manisan mangga Pasuruan yang mendunia...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1553356687-7a53f3718985?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 211,
            'slug_posts' => 'pabrik-elektronik-pasuruan',
            'judul_posts' => 'Peran Vital Pabrik Elektronik di Pasuruan dalam Rantai Pasok Global',
            'waktu_publish' => '2025-08-15 14:30:00',
            'konten_posts' => 'Menyerap ribuan tenaga kerja dan mendorong pertumbuhan ekonomi...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1596723363327-0473a644c32b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Joko Susilo']
        ],
        (object) [
            'id_posts' => 212,
            'slug_posts' => 'potensi-ekspor-bunga-krisan',
            'judul_posts' => 'Bunga Krisan Pasuruan Siap Memenuhi Pasar Ekspor',
            'waktu_publish' => '2025-08-14 10:00:00',
            'konten_posts' => 'Kualitas bunga potong dari dataran tinggi Pasuruan diminati pasar internasional...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1566873972236-418a032f2220?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 213,
            'slug_posts' => 'inovasi-produk-daur-ulang-plastik',
            'judul_posts' => 'Mengubah Sampah Menjadi Berkah: Inovasi Produk Daur Ulang Plastik',
            'waktu_publish' => '2025-08-13 16:20:00',
            'konten_posts' => 'Industri kreatif yang memberikan solusi bagi masalah lingkungan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1611270418597-a6c77f4b7271?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 214,
            'slug_posts' => 'sentra-kerajinan-kuningan',
            'judul_posts' => 'Kilau Kerajinan Kuningan dari Pengrajin Lokal',
            'waktu_publish' => '2025-08-12 11:45:00',
            'konten_posts' => 'Produk kerajinan tangan yang artistik dan bernilai jual tinggi...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1678235249673-c6c72a8187ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Joko Susilo']
        ],
        (object) [
            'id_posts' => 215,
            'slug_posts' => 'pengembangan-biogas-dari-limbah-ternak',
            'judul_posts' => 'Energi Terbarukan: Pengembangan Biogas dari Limbah Ternak',
            'waktu_publish' => '2025-08-11 09:00:00',
            'konten_posts' => 'Solusi energi alternatif sekaligus mengatasi masalah lingkungan...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1661963297349-f5383a8863f8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 216,
            'slug_posts' => 'industri-pakan-ternak',
            'judul_posts' => 'Menopang Sektor Peternakan: Industri Pakan Ternak di Pasuruan',
            'waktu_publish' => '2025-08-10 13:15:00',
            'konten_posts' => 'Memproduksi pakan berkualitas untuk meningkatkan produktivitas ternak...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1599422473854-47738c1171a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 217,
            'slug_posts' => 'pabrik-air-minum-cheers',
            'judul_posts' => 'Menjaga Kesegaran: Proses Produksi di Pabrik Air Minum Cheers',
            'waktu_publish' => '2025-08-09 15:30:00',
            'konten_posts' => 'Standar higienis tinggi untuk menghasilkan air minum yang sehat...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1556742044-1c34f762ce7c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Joko Susilo']
        ],
        (object) [
            'id_posts' => 218,
            'slug_posts' => 'industri-minuman-pocari-sweat',
            'judul_posts' => 'Di Balik Layar Industri Minuman Isotonik Pocari Sweat',
            'waktu_publish' => '2025-08-08 10:45:00',
            'konten_posts' => 'Pabrik modern yang menjadi salah satu investasi besar di Pasuruan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1621516264901-b33a7f827178?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Budi Hartono']
        ],
        (object) [
            'id_posts' => 219,
            'slug_posts' => 'hm-sampoerna-sejarah-industri-rokok',
            'judul_posts' => 'HM Sampoerna, Sejarah dan Kontribusi Industri Rokok',
            'waktu_publish' => '2025-08-07 14:00:00',
            'konten_posts' => 'Salah satu industri tertua yang terus beradaptasi dengan zaman...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1620912189836-15b947c14a2a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 220,
            'slug_posts' => 'industri-otomotif-yamaha',
            'judul_posts' => 'Perakitan Komponen Otomotif di Pabrik Yamaha Pasuruan',
            'waktu_publish' => '2025-08-06 11:30:00',
            'konten_posts' => 'Presisi dan teknologi tinggi dalam industri otomotif...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1593349315923-99d983a152d1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'industri', 'nama_kategori' => 'Industri'],
            'user_creator' => (object) ['nama_lengkap' => 'Joko Susilo']
        ],
        (object) [
            'id_posts' => 301,
            'slug_posts' => 'siswa-juara-olimpiade-sains',
            'judul_posts' => 'Siswa SMAN 1 Pasuruan Raih Medali Emas Olimpiade Sains Nasional',
            'waktu_publish' => '2025-08-25 10:00:00',
            'konten_posts' => 'Seorang siswa dari SMAN 1 Pasuruan berhasil mengharumkan nama daerah dengan meraih medali emas dalam ajang Olimpiade Sains Nasional (OSN)...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1576267423445-b2e0074d68a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Dispendik'],
        ],
        (object) [
            'id_posts' => 302,
            'slug_posts' => 'pasuruan-raih-adipura',
            'judul_posts' => 'Pasuruan Kembali Raih Penghargaan Adipura Kategori Kota Kecil',
            'waktu_publish' => '2025-08-24 15:30:00',
            'konten_posts' => 'Pemerintah Kabupaten Pasuruan menerima penghargaan Adipura sebagai pengakuan atas komitmen dalam menjaga kebersihan dan pengelolaan lingkungan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin DLH'],
        ],
        (object) [
            'id_posts' => 303,
            'slug_posts' => 'atlet-silat-medali-emas',
            'judul_posts' => 'Atlet Silat Asal Pasuruan Bawa Pulang Medali Emas dari Kejurprov',
            'waktu_publish' => '2025-08-23 12:00:00',
            'konten_posts' => 'Prestasi membanggakan diukir oleh pesilat muda di tingkat provinsi...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1678310348214-5264b92c41d1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Dispora']
        ],
        (object) [
            'id_posts' => 304,
            'slug_posts' => 'desa-wisata-terbaik-provinsi',
            'judul_posts' => 'Desa Kertosari Dinobatkan Sebagai Desa Wisata Terbaik Tingkat Provinsi',
            'waktu_publish' => '2025-08-22 17:00:00',
            'konten_posts' => 'Inovasi dan pengelolaan pariwisata berbasis masyarakat membuahkan hasil...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1516652362426-b375171a1795?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 305,
            'slug_posts' => 'puskesmas-akreditasi-paripurna',
            'judul_posts' => 'Puskesmas Gadingrejo Sukses Raih Akreditasi Paripurna',
            'waktu_publish' => '2025-08-21 11:30:00',
            'konten_posts' => 'Komitmen memberikan pelayanan kesehatan terbaik bagi masyarakat...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Dinkes']
        ],
        (object) [
            'id_posts' => 306,
            'slug_posts' => 'pemkab-pasuruan-opini-wtp',
            'judul_posts' => 'Untuk Kedelapan Kalinya, Pemkab Pasuruan Dapatkan Opini WTP dari BPK',
            'waktu_publish' => '2025-08-20 10:00:00',
            'konten_posts' => 'Bukti pengelolaan keuangan daerah yang transparan dan akuntabel...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1683140513988-12b23a7f832e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin BPKAD']
        ],
        (object) [
            'id_posts' => 307,
            'slug_posts' => 'tim-robotik-menang-internasional',
            'judul_posts' => 'Tim Robotik MTsN 1 Pasuruan Juarai Kontes Robot Internasional di Malaysia',
            'waktu_publish' => '2025-08-19 14:45:00',
            'konten_posts' => 'Inovasi teknologi dari para pelajar madrasah yang membanggakan Indonesia...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1681232371911-37f941f7d54b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Dispendik']
        ],
        (object) [
            'id_posts' => 308,
            'slug_posts' => 'sanggar-tari-juara-nasional',
            'judul_posts' => 'Sanggar Tari Tradisional Juarai Festival Nasional di Jakarta',
            'waktu_publish' => '2025-08-18 18:00:00',
            'konten_posts' => 'Melestarikan budaya lokal dan mengukir prestasi di kancah nasional...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1596205219446-f2868114f24f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
        (object) [
            'id_posts' => 309,
            'slug_posts' => 'umkm-inovatif-penghargaan-presiden',
            'judul_posts' => 'UMKM Inovatif Pasuruan Menerima Penghargaan Langsung dari Presiden',
            'waktu_publish' => '2025-08-17 11:00:00',
            'konten_posts' => 'Produk olahan pangan lokal berhasil menarik perhatian tingkat nasional...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disperindag']
        ],
        (object) [
            'id_posts' => 310,
            'slug_posts' => 'petani-kopi-sertifikasi-internasional',
            'judul_posts' => 'Petani Kopi Lereng Arjuno Sukses Mendapat Sertifikasi Internasional',
            'waktu_publish' => '2025-08-16 09:45:00',
            'konten_posts' => 'Pengakuan kualitas yang membuka pintu pasar ekspor lebih lebar...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1610612458693-8b776a0845cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Pertanian']
        ],
        (object) [
            'id_posts' => 311,
            'slug_posts' => 'penghargaan-sekolah-adiwiyata-mandiri',
            'judul_posts' => 'SMPN 2 Pasuruan Raih Penghargaan Sekolah Adiwiyata Mandiri',
            'waktu_publish' => '2025-08-15 13:00:00',
            'konten_posts' => 'Komitmen tinggi dalam menciptakan lingkungan sekolah yang hijau dan sehat...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin DLH']
        ],
        (object) [
            'id_posts' => 312,
            'slug_posts' => 'persekap-pasuruan-naik-kasta',
            'judul_posts' => 'Klub Sepakbola Persekap Pasuruan Berhasil Promosi ke Liga 2',
            'waktu_publish' => '2025-08-14 20:00:00',
            'konten_posts' => 'Perjuangan panjang yang berbuah manis bagi Laskar Sakera...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Dispora']
        ],
        (object) [
            'id_posts' => 313,
            'slug_posts' => 'juara-lomba-cipta-menu-b2sa',
            'judul_posts' => 'Tim PKK Pasuruan Juara 1 Lomba Cipta Menu B2SA Tingkat Jatim',
            'waktu_publish' => '2025-08-13 15:15:00',
            'konten_posts' => 'Kreasi menu beragam, bergizi, seimbang, dan aman berbasis pangan lokal...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1606787366850-de6330128214?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Ketahanan Pangan']
        ],
        (object) [
            'id_posts' => 314,
            'slug_posts' => 'polisi-teladan-penghargaan-kapolri',
            'judul_posts' => 'Bhabinkamtibmas Teladan Menerima Penghargaan dari Kapolri',
            'waktu_publish' => '2025-08-12 10:30:00',
            'konten_posts' => 'Dedikasi tinggi dalam melayani dan mengayomi masyarakat...',
            'gambar_posts' => 'https://plus.unsplash.com/premium_photo-1661898748369-a1789c675a89?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Humas Polres']
        ],
        (object) [
            'id_posts' => 315,
            'slug_posts' => 'koperasi-wanita-berprestasi-nasional',
            'judul_posts' => 'Koperasi Wanita "Sejahtera" Raih Gelar Koperasi Berprestasi Nasional',
            'waktu_publish' => '2025-08-11 11:00:00',
            'konten_posts' => 'Pemberdayaan ekonomi perempuan melalui koperasi yang sehat dan mandiri...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1620336237223-281b8319f357?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Diskoperindag']
        ],
        (object) [
            'id_posts' => 316,
            'slug_posts' => 'anugerah-paralegal-justice-award',
            'judul_posts' => 'Kepala Desa Gempol Raih Anugerah Paralegal Justice Award',
            'waktu_publish' => '2025-08-10 14:00:00',
            'konten_posts' => 'Berperan sebagai juru damai dalam menyelesaikan masalah warga...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1589216532372-1c2a36790039?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Hukum']
        ],
        (object) [
            'id_posts' => 317,
            'slug_posts' => 'medali-perak-pekan-olahraga-provinsi',
            'judul_posts' => 'Kontingen Pasuruan Bawa Pulang 15 Medali dari Pekan Olahraga Provinsi',
            'waktu_publish' => '2025-08-09 19:30:00',
            'konten_posts' => 'Perjuangan para atlet daerah yang patut diapresiasi...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1599551322154-20a2a5146197?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Dispora']
        ],
        (object) [
            'id_posts' => 318,
            'slug_posts' => 'penghargaan-kabupaten-layak-anak',
            'judul_posts' => 'Pasuruan Dianugerahi Penghargaan Kabupaten Layak Anak Peringkat Madya',
            'waktu_publish' => '2025-08-08 13:00:00',
            'konten_posts' => 'Komitmen pemerintah dalam pemenuhan hak dan perlindungan anak...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin DP3AKB']
        ],
        (object) [
            'id_posts' => 319,
            'slug_posts' => 'inovasi-pelayanan-publik-terbaik',
            'judul_posts' => 'Aplikasi "Lapor Pak" Menjadi Inovasi Pelayanan Publik Terbaik',
            'waktu_publish' => '2025-08-07 10:00:00',
            'konten_posts' => 'Mempermudah masyarakat dalam menyampaikan aspirasi dan pengaduan...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1556740738-b6a63e2775d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Kominfo']
        ],
        (object) [
            'id_posts' => 320,
            'slug_posts' => 'maestro-lukis-pameran-nasional',
            'judul_posts' => 'Maestro Lukis Lokal Gelar Pameran Tunggal di Galeri Nasional',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Karya-karya yang terinspirasi dari keindahan alam Pasuruan memukau ibukota...',
            'gambar_posts' => 'https://images.unsplash.com/photo-1547891654-e66ed711b999?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'prestasi', 'nama_kategori' => 'Prestasi'],
            'user_creator' => (object) ['nama_lengkap' => 'Admin Disparbud']
        ],
    ],
    'layanan' => [
        (object) [
            'id_posts' => 501,
            'slug_posts' => 'kartu-identitas-anak',
            'judul_posts' => 'Kartu Identitas Anak',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Kartu identitas anak dapat digunakan...',
            'gambar_posts' => 'https://disdukcapil.bulelengkab.go.id/uploads/konten/91_sekilas-tentang-kartu-identitas-anak.png',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'user'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/kartu-identitas-anak',
        ],
        (object) [
            'id_posts' => 502,
            'slug_posts' => 'akta-perkawinan-dan-perceraian',
            'judul_posts' => 'Akta Perkawinan dan Perceraian',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Akta Perkawinan dan Perceraian',
            'gambar_posts' => 'https://www.jakarta.go.id/uploads/contents/content--20230329064204.jpeg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/akta-perkawinan-dan-perceraian',
        ],
        (object) [
            'id_posts' => 503,
            'slug_posts' => 'akta-pencatatan-kematian',
            'judul_posts' => 'Akta Pencatatan Kematian',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => "Akta Pencatatan Kematian",
            'gambar_posts' => 'https://www.tintahijau.com/wp-content/uploads/2024/11/Akta-Kematian.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/akta-pencatatan-kematian',
        ],
        (object) [
            'id_posts' => 504,
            'slug_posts' => 'surat-mutasi-penduduk',
            'judul_posts' => 'Surat Mutasi Penduduk',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Surat Mutasi Penduduk',
            'gambar_posts' => 'https://asset.kompas.com/crops/NbwxMUhUBtERQDbUqyVwrIhR2cA=/0x0:919x613/1200x800/data/photo/2022/01/13/61e01d3e9937e.jpeg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/surat-mutasi-penduduk-skpwni-',
        ],
        (object) [
            'id_posts' => 505,
            'slug_posts' => 'ktp-elektronik',
            'judul_posts' => 'KTP Elektronik',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'KTP Elektronik',
            'gambar_posts' => 'https://asset-2.tribunnews.com/banjarmasin/foto/bank/images/Kantor-Disdukcapil-Kabupaten-HSU-di-Jalan-Karya-Manuntung-Kota-Raja-Kecamatan-Amuntai-Selatan.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/kartu-tanda-penduduk-elektronik-ktp---el-',
        ],
        (object) [
            'id_posts' => 506,
            'slug_posts' => 'sktt',
            'judul_posts' => 'SKTT',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'SKTT',
            'gambar_posts' => 'https://disdukcapil.bulelengkab.go.id/uploads/konten/33_aplikasi-aku-online-ng-mempermudah-pembuatan-sktt-bagi-warga-kabupaten-buleleng.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/sktt',
        ],
        (object) [
            'id_posts' => 507,
            'slug_posts' => 'kartu-keluarga',
            'judul_posts' => 'Kartu Keluarga',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Kartu Keluarga',
            'gambar_posts' => 'https://disdukcapil.bulelengkab.go.id/uploads/konten/21_mengubah-elemen-data-pada-kartu-keluarga.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/kartu-keluarga-kk',
        ],
        (object) [
            'id_posts' => 508,
            'slug_posts' => 'akta-pencatatan-sipil',
            'judul_posts' => 'Akta Pencatatan Sipil',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Akta Pencatatan Sipik',
            'gambar_posts' => 'https://dukcapil.bimakota.go.id/upload/kontent/363cfce41a814eb4987484003d08a9f1_foto%20kantor%20capil.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'kependudukan', 'nama_kategori' => 'Kependudukan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dispendukcapil.pasuruankab.go.id/halaman/akta-pencatatan-sipil',
        ],
        (object) [
            'id_posts' => 509,
            'slug_posts' => 'pengujian-kendaraan-bermotor',
            'judul_posts' => 'Pengujian Kendaraan Bermotor',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pengujian Kendaraan Bermotor',
            'gambar_posts' => 'https://koransatu.id/wp-content/uploads/2023/03/798DA6BD-A18B-4F5F-918D-BA99D57017ED.jpeg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'perhubungan', 'nama_kategori' => 'Perhubungan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dishub.pasuruankab.go.id/pages/ujikir',
        ],
        (object) [
            'id_posts' => 510,
            'slug_posts' => 'ramp-check',
            'judul_posts' => 'Ramp Check',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Ramp Check',
            'gambar_posts' => 'https://cdn.rri.co.id/berita/Samarinda/o/1741590849354-WhatsApp_Image_2025-03-10_at_15.12.25/ar9i51ypnsnbg7v.jpeg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'perhubungan', 'nama_kategori' => 'Perhubungan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dishub.pasuruankab.go.id/pages/rampcek',
        ],
        (object) [
            'id_posts' => 511,
            'slug_posts' => 'perizinan-angkutan',
            'judul_posts' => 'Perizinan Angkutan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Perizinan Angkutan',
            'gambar_posts' => 'https://redaksi8.com/wp-content/uploads/2025/08/mutlgurov1QwSIpUdDEHoJsapQvdVcaa9RtpKIh4.jpeg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'perhubungan', 'nama_kategori' => 'Perhubungan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dishub.pasuruankab.go.id/pages/angkut',
        ],
        (object) [
            'id_posts' => 512,
            'slug_posts' => 'perizinan-perparkiran',
            'judul_posts' => 'Perizinan Perpakiran',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Perizinan Perpakiran',
            'gambar_posts' => 'https://static.promediateknologi.id/crop/0x0:2303x1479/0x0/webp/photo/p2/72/2024/09/12/IMG20240912125027-30218754.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'perhubungan', 'nama_kategori' => 'Perhubungan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dishub.pasuruankab.go.id/pages/parkir',
        ],
        (object) [
            'id_posts' => 513,
            'slug_posts' => 'analisis-dampak-lalu-lintas',
            'judul_posts' => 'Analisis Dampak Lalu Lintas',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Analisis Dampak Lalu Lintas',
            'gambar_posts' => 'https://dishub.sanggau.go.id/uploads/a998a05fc927aeb7f5cc4dd2abcf3c56a31f8629c42b6400.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'perhubungan', 'nama_kategori' => 'Perhubungan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dishub.pasuruankab.go.id/pages/andalalin',
        ],
        (object) [
            'id_posts' => 514,
            'slug_posts' => 'pengaduan-pju-kabupaten-pasuruan',
            'judul_posts' => 'Pengaduan PJU Kabupaten Pasuruan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pengaduan PJU Kabupaten Pasuruan',
            'gambar_posts' => 'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/100/2025/07/15/WhatsApp-Image-2025-07-15-at-103135-2791807237.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'perhubungan', 'nama_kategori' => 'Perhubungan'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dishub.pasuruankab.go.id/pages/adupju',
        ],
        (object) [
            'id_posts' => 515,
            'slug_posts' => 'pelayanan-konsultasi-tik-pada-aplikasi-sakti',
            'judul_posts' => 'Pelayanan Konsultasi TIK Pada Aplikasi SAKTI',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Konsultasi TIK Pada Aplikasi SAKTI',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage/berita202507/1553-688992e64421b.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-konsultasi-tik-pada-aplikasi-sakti',
        ],
        (object) [
            'id_posts' => 516,
            'slug_posts' => 'layanan-nomor-tunggal-panggilan-darurat-112',
            'judul_posts' => 'Layanan Nomor Tunggal Panggilan Darurat 112',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Layanan Nomor Tunggal Panggilan Darurat 112',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage//halaman202405/79-664c949645c08.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/layanan-nomor-tunggal-panggilan-darurat-112',
        ],
        (object) [
            'id_posts' => 517,
            'slug_posts' => 'pelayanan-pengaduan',
            'judul_posts' => 'Pelayanan Pengaduan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Pengaduan',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage//halaman202405/77-664c92ea0e10c.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-pengaduan',
        ],
        (object) [
            'id_posts' => 518,
            'slug_posts' => 'pelayanan-sub-domain-hosting-dan-vps',
            'judul_posts' => 'Pelayanan Sub Domain, Hosting dan VPS',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Sub Domain, Hosting dan VPS',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage/file_media/d5fc87ad4ebb19acb18dfac790c4fe6f.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-sub-domain-hosting-dan-vps',
        ],
        (object) [
            'id_posts' => 519,
            'slug_posts' => 'pelayanan-gangguan-jaringan-internet-lan',
            'judul_posts' => 'Pelayanan Gangguan Jaringan Internet/LAN',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Gangguan Jaringan Internet/LAN',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage//halaman202405/82-664c956c50351.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-gangguan-jaringan-internet-lan',
        ],
        (object) [
            'id_posts' => 520,
            'slug_posts' => 'pelayanan-pengajuan-keamanan-sistem-informasi',
            'judul_posts' => 'Pelayanan Pengajuan Keamanan Sistem Informasi',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Pengajuan Keamanan Sistem Informasi',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage//halaman202405/84-664c96124408f.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-pengajuan-keamanan-sistem-informasi',
        ],
        (object) [
            'id_posts' => 521,
            'slug_posts' => 'pelayanan-permohonan-penyelenggaraan-video-conference',
            'judul_posts' => 'Pelayanan Permohonan Penyelenggaraan Video Conference',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Permohonan Penyelenggaraan Video Conference',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage/berita202408/1443-66cf22e771201.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-permohonan-penyelenggaraan-video-conference',
        ],
        (object) [
            'id_posts' => 522,
            'slug_posts' => 'pelayanan-sandi-dan-telekomunikasi',
            'judul_posts' => 'Pelayanan Sandi dan Telekomunikasi (Santel)',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Sandi dan Telekomunikasi (Santel)',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage//halaman202405/85-664c9649617be.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-sandi-dan-telekomunikasi-santel',
        ],
        (object) [
            'id_posts' => 523,
            'slug_posts' => 'pelayanan-sosialisasi-permohonan-narasumber-terkait-aplikasi',
            'judul_posts' => 'Pelayanan Sosialisasi Permohonan Narasumber Terkait Aplikasi',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Pelayanan Sosialisasi Permohonan Narasumber Terkait Aplikasi',
            'gambar_posts' => 'https://diskominfo.pasuruankab.go.id/storage//halaman202405/87-664c96d84348e.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'informasi-komunikasi', 'nama_kategori' => 'Informasi & Komunikasi'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://diskominfo.pasuruankab.go.id/halaman/pelayanan-sosialisasi-permohonan-narasumber-terkait-aplikasi',
        ],
        (object) [
            'id_posts' => 524,
            'slug_posts' => 'sektor-peternakan',
            'judul_posts' => 'Sektor Peternakan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Peternakan',
            'gambar_posts' => 'https://disnakkp.pasuruankab.go.id/storage/berita202507/1051-6881811ee5d7d.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-peternakan',
        ],
        (object) [
            'id_posts' => 525,
            'slug_posts' => 'sektor-perikanan',
            'judul_posts' => 'Sektor Perikanan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Perikanan',
            'gambar_posts' => 'https://pasuruankab.go.id/download-file/eyJpdiI6InZaR1QrK1ZqUVNRZjQyd2VZbVNqdWc9PSIsInZhbHVlIjoiVFR4amJ3dnBMa045Z3JWbVJuYWE5UT09IiwibWFjIjoiNTIzNDQ2ZWJmMmRlMjIzZWVkOWNkZDc3YjU1NDNjYWM4NDA3NTg2M2M2MTM2NmYyODgxNzgyN2RiMTMzZjI3YyIsInRhZyI6IiJ9/posts/gambar_posts/berita',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-perikanan',
        ],
        (object) [
            'id_posts' => 526,
            'slug_posts' => 'sektor-perhubungan',
            'judul_posts' => 'Sektor Perhubungan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Perhubungan',
            'gambar_posts' => 'https://kabarbaik.co/wp-content/uploads/2025/08/WhatsApp-Image-2025-08-23-at-11.14.54.jpeg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-perhubungan',
        ],
        (object) [
            'id_posts' => 527,
            'slug_posts' => 'sektor-pariwisata',
            'judul_posts' => 'Sektor Pariwisata',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Pariwisata',
            'gambar_posts' => 'https://api.minio.jatimprov.go.id/kominfo-jatim/images/0%20PAD%20Kabupaten%20Pasuruan%20Tahun%202024%20Dari%20Sektor%20Wisata%20Melebihi%20Target.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-pariwisata',
        ],
        (object) [
            'id_posts' => 528,
            'slug_posts' => 'sektor-sosial',
            'judul_posts' => 'Sektor Sosial',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Sosial',
            'gambar_posts' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIR8K8e_JCQ8_N825RiudMSB8PVoe4i3e89g&s',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-sosial',
        ],
        (object) [
            'id_posts' => 529,
            'slug_posts' => 'sektor-tenaga-kerja',
            'judul_posts' => 'Sektor Tenaga Kerja',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Tenaga Kerja',
            'gambar_posts' => 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjnmZcj-2uXhR5BEW051-bhQRh7_PQrPdqaQ06i3cF5B1LNybXkocyjF1jz9tcjzg3OHaLHPECKFqU37CD2Rb__P-03NG7qC-PHlYoXahHcKnAHE872TZZeDHpy68732T90-f2eoKQunP2rlidEpwS9gTF3Fwy_i4dU7MNS4uORHYOQAJUmJn_9fIIKzNEb/s4160/IMG_20241212_121433.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-tenaga-kerja',
        ],
        (object) [
            'id_posts' => 530,
            'slug_posts' => 'sektor-kesehatan',
            'judul_posts' => 'Sektor Kesehatan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Kesehatan',
            'gambar_posts' => 'https://dialogmasa.com/wp-content/uploads/2024/09/IMG-20240911-WA0124-scaled.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-kesehatan',
        ],
        (object) [
            'id_posts' => 531,
            'slug_posts' => 'sektor-pendidikan',
            'judul_posts' => 'Sektor Pendidikan',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Pendidikan',
            'gambar_posts' => 'https://pasuruankab.go.id/download-image/pembinaan-ratusan-kepala-sekolah-negeri-mas-bupati-rusdi-kami-ingin-kerjasama-bapak-ibu-maksimalkan-kualitas-pelayanan-pendidikan/posts/gambar_posts',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-pendidikan',
        ],
        (object) [
            'id_posts' => 532,
            'slug_posts' => 'sektor-pekerjaan-umum',
            'judul_posts' => 'Sektor Pekerjaan Umum',
            'waktu_publish' => '2025-08-06 16:45:00',
            'konten_posts' => 'Sektor Pekerjaan Umum',
            'gambar_posts' => 'https://taligama.com/wp-content/uploads/2022/06/IMG-20220630-WA0004.jpg',
            'gambar_posts_2' => null,
            'kategori' => (object) ['slug_kategori' => 'umum-perijinan', 'nama_kategori' => 'UMUM/PERIJINAN'],
            'user_creator' => (object) ['nama_lengkap' => 'User'],
            'external_url' => 'https://dpmptsp.pasuruankab.go.id/halaman/sektor-pekerjaan-umum',
        ],
    ],
];
