on:
  push:
    branches:
      - main

name: 🚀 Deploy master on push

jobs:
  web-deploy:
    name: 🎉 Deploy to main
    runs-on: ubuntu-latest
    environment: production
    concurrency: master-deploy
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v2

      - name: 🚀 Deploy via FTP (dry-run)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_PRODUCTION }}
          username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
          password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
          port: 21
          protocol: ftp
          server-dir: ./laravel/              # karena FTP login langsung ke folder subdomain
          local-dir: ./               # semua isi repo akan diupload
          dry-run: false               # test dulu tanpa benar-benar mengupload
          allow-delete: true             # hapus file lama yang tidak ada di local
          continue-on-error: true        # skip file/folder yang tidak ada
