name: 🚀 Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to production
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: master-deploy
      cancel-in-progress: true

    steps:
      # 1️⃣ Checkout repository
      - name: 📦 Checkout code
        uses: actions/checkout@v2

      # 2️⃣ Deploy via FTP (stabil, no 550 errors)
      - name: 🚀 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.FTP_SERVER_PRODUCTION }}
          username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
          password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
          port: 21
          protocol: ftp
          local-dir: ./                  # semua isi repo
          server-dir: ./laravel/         # sesuaikan path Laravel di server
          dry-run: false
          allow-delete: false            # jangan hapus file/folder lama → hindari error 550
          continue-on-error: true        # skip file/folder yang hilang

      # 3️⃣ (Opsional) Clear Laravel cached views via URL
      # Pastikan ada route/artisan command di server yang bisa dipanggil
      - name: ⚡ Clear Laravel cached views
        run: |
          curl -s -X GET https://${{ secrets.SERVER_URL }}/artisan-view-clear || true
