on:
  push:
    branches:
      - main

name: 🚀 Deploy master on push

jobs:
  web-deploy:
    name: 🎉 Deploy to main
    runs-on: ubuntu-latest
    environment: production
    concurrency: master-deploy
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v2

      - name: 🚀 Deploy via FTP (dry-run)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_PRODUCTION }}
          username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
          password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
          port: 21
          protocol: ftp
          local-dir: ./                  # semua isi repo
          server-dir: ./laravel/         # pastikan sesuai FTP
          dry-run: false
          allow-delete: false            # jangan hapus file/folder lama
          continue-on-error: true        # skip file/folder yang hilang


          
